package Repos;

import java.sql.Connection;

public class AccountsRepository {
    private Connection connection;

    private String CreateTableSQL = "CREATE TABLE Accounts(" +
            "ID int GENERATED BY DEFAULT AS IDENTITY" +
            "RepairID int" +
            "HistoryID int" +
            "ProfileID int" +
            ")";
}
