package Repos;

import java.sql.Connection;

public class ProfileRepository {
    private Connection connection;

    private String CreateTableSQL = "CREATE TABLE Profile(" +
            "ID int GENERATED BY DEFAULT AS IDENTITY" +
            "Name VARCHAR (30)" +
            "Surname VARCHAR(40)" +
            "Email VARCHAR(50)" +
            "Password VARCHAR (18)" +
            ")";
}
